-- AlterTable
ALTER TABLE "ute_processes" ALTER COLUMN "consultaSentAt" SET DATA TYPE DATE,
ALTER COLUMN "caseOpenedAt" SET DATA TYPE DATE,
ALTER COLUMN "consultaApprovedAt" SET DATA TYPE DATE,
ALTER COLUMN "solicitudSentAt" SET DATA TYPE DATE,
ALTER COLUMN "proyectoApprovedAt" SET DATA TYPE DATE,
ALTER COLUMN "docs1SentAt" SET DATA TYPE DATE,
ALTER COLUMN "docs1ApprovedAt" SET DATA TYPE DATE,
ALTER COLUMN "ensayosSentAt" SET DATA TYPE DATE,
ALTER COLUMN "ensayosApprovedAt" SET DATA TYPE DATE,
ALTER COLUMN "docs2SentAt" SET DATA TYPE DATE,
ALTER COLUMN "finalizedAt" SET DATA TYPE DATE;
