// Mappings portados de DOCs_UTE_personas.py.
// Cada función recibe el set de variables ya construido y devuelve la lista
// plana de strings, en el orden en que las coordenadas las consumen. El largo
// de cada lista DEBE coincidir con el total de coords del doc (sumando páginas).

import type { UteVariables } from "./variables.js";

export type DocMapping = (v: UteVariables) => string[];

export const MAPPINGS: Record<string, DocMapping> = {
  solicitud_img: (v) => [
    v.Cliente,
    v.Cliente,
    v.Mail_cliente,
    v.Telefono_cliente,
    v.Cuenta,
    v.Caso,
    v.Pot_contratada_1000,
    v.Tarifa,
    v.Dir_cliente,
    v.Ciudad,
    v.Depto,
    v.Persona_Fisica,
    v.Empresa,
    v.CI_cliente,
    v.Potencia_nom_solicitud_IMG,
    v.Intensidad_nom_solicitud_IMG,
    v.Tension_230,
    v.Tension_400,
    v.Fases_mono,
    v.Fases_tri,
    v.Cantidad_paneles,
    v.Cantidad_inversores,
    v.Pot_tot_paneles,
    v.Area_paneles,
    v.Tipo_generador_Sinc_tri,
    v.Tipo_generador_Sinc_mono,
    v.Marca_panel,
    v.Modelo_panel,
    v.Serie_panel,
    v.Pot_panel,
    v.Marca_inversor,
    v.Modelo_inversor,
    v.Serie_inversor,
    v.Tension_nom_inversor_230,
    v.Tension_nom_inversor_400,
    v.Tipo_generador_Sinc_mono,
    v.Tipo_generador_Sinc_tri,
    v.Potencia_nom_inversor,
  ],

  dar: (v) => [
    v.Ciudad,
    v.Dia1,
    v.Mes2,
    v.Año1,
    v.FI,
    v.RUT,
    v.Dir_FI,
    v.TI,
    v.CI_TI,
    v.Cliente,
    v.CI_cliente,
    v.Dir_cliente,
    v.Dir_cliente,
    v.AS,
    v.Cuenta,
    v.X,
    v.RUT,
    v.TI,
    v.CI_TI,
    v.TI,
    v.Oficina,
    v.CI_cliente,
    v.Cliente,
    v.Cliente,
    v.Dia1,
    v.Mes2,
    v.Año1,
  ],

  jurada_min: (v) => [
    v.Representa,
    v.CI_Repre,
    v.Cliente,
    v.CI_cliente,
    v.Calle,
    v.Num_calle,
    v.Ciudad,
    v.Depto,
    v.Calidad_Repre,
    v.Cuenta,
    v.PS,
    v.Ciudad,
    v.Oficina,
    v.CI_cliente,
    v.Cliente,
    v.Dia1,
    v.Mes2,
    v.Año1,
  ],

  jurada_tec: (v) => [
    v.FI,
    v.RUT,
    v.TI,
    v.CI_TI,
    v.TI,
    v.CI_TI,
    v.Cliente,
    v.Cuenta,
    v.PS,
    v.normas1,
    v.normas2,
    v.X,
    v.Ciudad,
    v.RUT,
    v.TI,
    v.CI_TI,
    v.TI,
    v.Oficina,
    v.Dia1,
    v.Mes2,
    v.Año1,
    v.Dia1,
    v.Mes2,
    v.Año1,
    v.x1,
    v.x2,
    v.x3,
    v.x4,
  ],

  // Convenio: el array sigue el orden página → página (saltando las null).
  // El llamador no necesita preocuparse: el generator zipea coords y datos
  // por página, respetando los null como "no overlay".
  convenio: (v) => [
    // página 3
    v.Ciudad,
    v.Dia1,
    v.Mes2,
    v.Año1_corto,
    v.Rep_UTE,
    v.Calidad_UTE,
    v.Cliente,
    v.CI_cliente,
    v.Calle,
    v.Num_calle,
    v.Cliente,
    v.Calidad_Repre,
    v.CI_cliente,
    // página 5
    v.Calle,
    v.Num_calle,
    v.PS,
    // página 6
    v.X,
    v.Pot_IMG,
    v.Pot_IMG_letras,
    v.Pot_contratada,
    v.Pot_contratada_letras,
    v.Pot_IMG,
    v.Pot_IMG_letras,
    // página 7
    v.fp,
    // página 14
    v.Cliente,
    v.Dir_cliente,
    v.Mail_cliente,
  ],

  sol_hab: (v) => [
    v.Ciudad,
    v.Dia_fin,
    v.Mes_fin,
    v.Año_fin,
    v.Cliente,
    v.CI_cliente,
    v.FI,
    v.RUT,
    v.TI,
    v.CI_TI,
    v.TI,
    v.CI_TI,
    v.Dia1,
    v.Mes2,
    v.Año1,
    v.Cuenta,
    v.PS,
    v.CI_cliente,
    v.Cliente,
    v.RUT,
    v.TI,
    v.CI_TI,
    v.TI,
    v.Oficina,
  ],

  acta_hab: (v) => [
    v.Ciudad,
    v.Dia_fin,
    v.Mes_fin,
    v.Año_fin,
    v.Cliente,
    v.CI_cliente,
    v.FI,
    v.RUT,
    v.TI,
    v.CI_TI,
    v.TI,
    v.CI_TI,
    v.Dia1,
    v.Mes2,
    v.Año1,
    v.Cuenta,
    v.PS,
    v.CI_cliente,
    v.Cliente,
    v.RUT,
    v.TI,
    v.CI_TI,
    v.TI,
    v.Oficina,
  ],

  contrato: (v) => [
    // página 1
    v.Ciudad,
    v.Dia_fin,
    v.Mes_fin,
    v.Año1_corto,
    v.Rep_UTE,
    v.Calidad_UTE,
    v.Cliente,
    v.CI_cliente,
    v.Calle,
    v.Num_calle,
    v.Representa,
    v.Calidad_Repre,
    v.CI_Repre,
    // página 2
    v.Dir_cliente,
    v.Ciudad,
    v.Depto,
    v.Cuenta,
    v.PS,
    v.Pot_contratada,
    v.Dia1,
    v.Mes1,
    v.Año1_corto,
    v.Pot_IMG,
    v.Pot_IMG,
  ],
};
